// JavaScript Document
Ext.define('Ext.mod.model.Patient',{
	extend:'Ext.data.Model',
	fields:[
		{name:'patient_id',type:'integer'},
		{name:'patientname',type:'string'},
		{name:'patientlastname',type:'string'},
		{name:'patronymic',type:'string'},
		{name:'country_id',type:'integer'},
		{name:'country_name',type:'string'},
		{name:'city_id',type:'integer'},
		{name:'city_name',type:'string'},
		{name:'personalid',type:'string'},
		{name:'history_id',type:'string'},
		{name:'birthday',type:'integer'},
		{name:'gendercode',type:'integer'},
		{name:'gender',type:'string'},
		{name:'phone1',type:'string'},
		{name:'phone2',type:'string'},
		{name:'email',type:'string'},
		{name:'address1',type:'string'},
		{name:'address2',type:'string'},
		{name:'work_phone',type:'string'},
		{name:'work',type:'string'},
		{name:'editorcode',type:'string'}
	],
});