// JavaScript Document
Ext.define('Ext.mod.model.SearchPatients',{
	extend:'Ext.data.Model',
	fields:[
		{name:'patient_id',type:'integer'},
		{name:'reg_id',type:'integer'},
		{name:'patientlastname', type:'string'},
		{name:'patientname', type:'string'},
		{name:'birthday', type:'string'},
		{name:'patronymic',type:'string'},
		{name:'country_id',type:'integer'},
		{name:'country_name',type:'string'},
		{name:'ccountry_id',type:'integer'},
		{name:'ccountry_name',type:'string'},
		{name:'city_id',type:'integer'},
		{name:'city_name',type:'string'},
		{name:'personalid',type:'string'},
		{name:'history_id',type:'string'},
		{name:'gendercode',type:'integer'},
		{name:'gender',type:'string'},
		{name:'phone1',type:'string'},
		{name:'phone2',type:'string'},
		{name:'email',type:'string'},
		{name:'address1',type:'string'},
		{name:'address2',type:'string'},
		{name:'work_phone',type:'string'},
		{name:'work',type:'string'},
		{name:'editorcode',type:'string'},
		{name:'transdate', type:'string'},
		{name:'clinic_id', type:'integer'},
		{name:'clinic', type:'string'},
		{name:'donor_type_id', type:'integer'},
		{name:'donor', type:'string'},
		{name:'donor_info', type:'string'},
		{name:'doctor_id', type:'integer'},
		{name:'operator_id', type:'integer'},
		{name:'docname', type:'string'},
		{name:'doclastname', type:'string'},
		{name:'opname', type:'string'},
		{name:'oplastname', type:'string'},
		{name:'diagnosis_id', type:'integer'},
		{name:'diagnosis', type:'string'},
		//{name:'medicine_id', type:'integer'},
		{name:'medicine', type:'string'},
        {name:'dosage', type:'string'},
		{name:'con_date', type:'string'},
		{name:'condition', type:'string'},
		{name:'dialysis_date', type:'string'},
		{name:'dialysis', type:'string'},
		{name:'blood_type_id', type:'integer'},
		{name:'rhesus', type:'integer'},
		{name:'info', type:'string'},
		{name:'category_id', type:'integer'},
		{name:'category', tydpe:'string'},
		{name:'regdate', type:'string'},
		{name:'removaldate', type:'string'},
		{name:'removal', type:'string'},
		{name : 'pimage', type: 'auto'}
	],
});